### ISSUE TITLE
lavaanPlot not displaying anything in Google Colab/Jupyter notebook

### ISSUE THREAD

**Issue by AlejandroDGR** [alishinski/lavaanPlot#43]
Hi,

I'm trying to use lavaanPlot() in a Google Colab notebook with the following code:
```
lavaanPlot(model = my_model,  node_options = list(shape = "box", fontname = "Helvetica"), edge_options = list(color = "grey"), coefs = TRUE)
```
It does not arise any error, but, however, it isn't displaying anything.

Any idea why is it happening?

(By the way, last version of lavaan doesn't arise the disere summary output format, so I've had to install the previous package version to solve it. I'vre tried the same for lavaanPlot, but it doesn't work).

**Comment by alishinski** [comment]
There's a lot that I don't know about how that environment works, so there's a lot of reasons the plots wouldn't show up right, because the way they are rendered in r relies on a complicated set of tools. The best I could say is to try saving plots as images and insert them into your notebook that way.
